### ISSUE TITLE
Maps not visible on second form

### ISSUE THREAD

**Issue by dekosan** [EtheaDev/DelphiGoogleMap#1]
When putting the TEdgeGoogleMapViewer in a new VCL project on Form1 it works fine, a very nice component!
However when putting the TEdgeGoogleMapViewer on a second new form2, opened by the main form1, the map is not visible.
Any help is welcome!
Thanks

**Comment by carloBarazzetta** [comment]
I've updated the component to setup a cache folder for temp files.
I've also added a second form to test multiple instance of component and it works fine to me: please check the demo.

**Comment by dekosan** [comment]
Thanks Carlo,
This works fine for me. The difference is indeed the way the second form is created. 
Also the addition of the UserDataFolder is useful. 
Kind regards,
Jozef

.
