### ISSUE TITLE
rectangle

### ISSUE THREAD

**Issue by Raymond-Ng** [EtheaDev/DelphiGoogleMap#10]
possible to support drawing rectangle ?

**Comment by carloBarazzetta** [comment]
I've added a section "How it works!" in readme.md file.
You can do anything you want, putting a javascript function inside the page built by the component and then call it by ExecuteJavascript method. Please read the explanation inside Readme.

**Comment by Raymond-Ng** [comment]
I mean can it support Poligon ? any sample javascript available?

**Comment by carloBarazzetta** [comment]
No, I don't know what can you do, and I'm not a javascript expert... You can integrate in the component any Javascript function you can write inside the WEB page that can interactive with del Google Map Object, Look at the Google Maps API to extend this component, as I made for the existing functions of my component. Search for javascript examples in the web.
