### ISSUE TITLE
Initialization issue

### ISSUE THREAD

**Issue by vpapanik** [EtheaDev/DelphiGoogleMap#18]
Thanks a lot for your excellent component !!! It is mostly helpful.

I would like to report an Issue regarding the initial map.
In the demo, I have to first press 'hide map' and then 'show map' to get a map image.
The map is not 'clean' since it contains a marker, a circle and a few more elements.

When I delete those element and then check 'Map Type' they show all over again !

In my own code, I am just using GotoLocation(LatLng) and I get the same 'dirty' image the first time. I have to manually delete all those elements.

Is there a workaround to this ?

**Comment by vpapanik** [comment]
A working initialization process I found is

GoogleMapViewer.ShowMap('');

GoogleMapViewer.ClearMarkers;
GoogleMapViewer.ClearCircles;
GoogleMapViewer.ClearPolylines;
GoogleMapViewer.ClearPolygons;

LatLng.Latitude := edit_Lat.FloatValue;
LatLng.Longitude := edit_Lng.FloatValue;

GoogleMapViewer.GotoLocation(LatLng);

**Comment by carloBarazzetta** [comment]
Have you modified line 675 of the MainForm.pas demo to configure your GoogleMapsApiKey?

**Comment by vpapanik** [comment]
Of course, the map works but I get those unwanted elements...

**Comment by carloBarazzetta** [comment]
If you want to check the problem you can change line 940 of Vcl.GoogleMap.pas to {$IFDEF DEBUG} and rebuild Demo in Debug Mode. Now the component uses a File to show the map, so you can use the static file created in the temp user folder to load into a Browser and activate debug/console panel to check if there are some problems...

**Comment by vpapanik** [comment]
I found a nice workaround :

I display the map (with the extra stuff) using :

EdgeGoogleMapViewer.GotoLocation(LatLng);

and then I erase those default elements on the OnNavigationCompleted event :

EdgeGoogleMapViewer.ClearMarkers;
EdgeGoogleMapViewer.ClearCircles;
EdgeGoogleMapViewer.ClearPolylines;
EdgeGoogleMapViewer.ClearPolygons;

The problem is that those dummy elements are always created in TEdgeGoogleMapViewer.GetJSInitialize

`  '    PutMarker(latlng.lat(), latlng.lng(), %s);'+sLineBreak+
  '    PutCircle(latlng.lat(), latlng.lng(), 33333, false, false, true, true, "#FF0000", 0.80, 2, "#FF0000", 0.35, "");'+sLineBreak+
  '    PutPolyline([ { lat: 40.7128, lng: -74.0060 },{ lat: 34.0522, lng: -118.2437 },{ lat: 41.8781, lng: -87.6298 } ], false, true, true, true, false, "#FF0000", 0.80, 2, "Polyline Sample");'+sLineBreak+
  '    PutPolygon([ { lat: 45.5868, lng: 9.2709}, { lat: 45.5876, lng: 9.2794 },{ lat: 45.5817, lng: 9.2809 },{ lat: 45.5815, lng: 9.2721 } ], true, true, true, false, "#FF0000", 0.80, 2, "#FFFF00", 0.80, "Poligon Sample");'+sLineBreak+
`
