### ISSUE TITLE
.WebView2 generated folder

### ISSUE THREAD

**Issue by vpapanik** [EtheaDev/DelphiGoogleMap#19]
Is it possible to redirect the generated folder <app name>.WebView2 from the app folder to Temp folder ?

**Comment by carloBarazzetta** [comment]
Yes, as you can see in the demo initialization section of MainForm.pas
  //Setup UserDataFolder for Temp files
  TEdgeGoogleMapViewer.RegisterUserDataFolder(System.IOUtils.TPath.GetTempPath+ExtractFileName(ParamStr(0)));

**Comment by vpapanik** [comment]
Thanks a lot ! I placed it in FormCreate instead of initialization section. Now it works !
