### ISSUE TITLE
Component installation error

### ISSUE THREAD

**Issue by rzakfirst** [EtheaDev/DelphiGoogleMap#3]
property BrowserExecutableFolder;
    property UserDataFolder;

Returns error with Delphi 10.4

**Comment by aangelov971** [comment]
I try to compile error appears 
[dcc32 Fatal Error] Vcl.GoogleMap.pas(1): Internal Error: AV004778D9-R00000000-0
I read about error and set delphi compiler option to MSBuild externaly to true. error continue toa apear. It's not a syntax error. What should I do next?
