### ISSUE TITLE
Problem with dll , form/unit name and declaring apikey 

### ISSUE THREAD

**Issue by anastasangelov** [EtheaDev/DelphiGoogleMap#5]
_Originally posted by @aangelov971 in https://github.com/EtheaDev/DelphiGoogleMap/issues/4#issuecomment-1094104109_

1. I instaled everything seems good with installation but when I run demo or create simple app error " webview2loader check if present" apears.
2. Error with SecondaryForm (form) and FormSeconadary (unit) error is present also, but that is easy to solve
3. Property TEdgeGoogleMapViewer.ApiKey is readonly and I can't put string in EdgeGoogleMapViewerBeforeShowMap event. Can you see what is wrong? (TEdgeGoogleMapViewer.ApiKey:=' someApikey'; )

**Comment by carloBarazzetta** [comment]
Using the test app, and putting my personal google API Key in the "initialization" section, it works fine:

``` Delphi
  //If you have a Google API Key it's time to setup
  TEdgeGoogleMapViewer.RegisterGoogleMapsApiKey('AIzaSyBNY0ARa4xxxxxxxxxxxxNp96yM3dgHg');

```
![image](https://user-images.githubusercontent.com/7803548/162616054-3feca8fc-4e80-4169-b40c-3d99173adea3.png)

**Comment by anastasangelov** [comment]
Yes, problem is on my side,probably JS and Edge Browser. Ty Carlo. I will solve problem.
