### ISSUE TITLE
show /hide controls

### ISSUE THREAD

**Issue by tbegsr** [EtheaDev/DelphiGoogleMap#7]
Hi 

Thank you for your project.

I’ve included some code to allow show /hide controls
I’ve marked each change with gsr. Perhaps you can include this code

FullScreenControl
MapTypeControl
ZoomControl

And perhaps something for the demo which allow to save the map to a file

  EdgeGoogleMapViewer.CapturePreview (System.SysUtils.ExtractFilePath(
        System.ParamStr(0))+'CapturePreview01.jpg',JPEG);

PNG is also working

Regards Rolf

[Vcl.GoogleMap.pas.txt](https://github.com/EtheaDev/DelphiGoogleMap/files/10095792/Vcl.GoogleMap.pas.txt)

**Comment by carloBarazzetta** [comment]
Thanks for your work, I'm thinking of including in the source code...

**Comment by carloBarazzetta** [comment]
Integrated into v1.4.0
