### ISSUE TITLE
read values ​​from queries

### ISSUE THREAD

**Issue by tbegsr** [EtheaDev/DelphiGoogleMap#8]
I have a question. Is it possible to read values ​​from queries.
I need the coordinates from an adress codeAddress(address)
and and the json object for the direction

**Comment by carloBarazzetta** [comment]
I don't know.

**Comment by carloBarazzetta** [comment]
I've added more help into readme.md, I hope to help you: if you can do your job via javascript it's quite simple to add to the Delphi component, as explained.

**Comment by spedroas** [comment]
Good morning, here in Brazil. Please, could you help me with the following situation... I installed and compiled the component, but when executing the code, the attached message appears. Both for the main form and the second form. I am not able to view the HTML file and where you can see it being executed by Delphi 11.

<img width="955" alt="Não carrega a página" src="https://github.com/EtheaDev/DelphiGoogleMap/assets/134372873/09dc7210-161c-4410-a28b-a953a685b8a6">

<img width="957" alt="Não carrega a página_FormMain" src="https://github.com/EtheaDev/DelphiGoogleMap/assets/134372873/d16203ee-e834-4442-a021-151bcd8b82df">

**Comment by carloBarazzetta** [comment]
it seems that you never acquire the Google API key to activate the navigation, as explained in readme file.

**Comment by spedroas** [comment]
Thanks for the answer. But I activated the API Key and the message appears when trying to display the map in EdgeGoogleMapViewer.

**Comment by carloBarazzetta** [comment]
Try to test your API KEY calling this URL:
https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=XXXXXXXXXXXXXXXXXXXXXXXXXX

To see the HTML file produced, you can place a breakpoint into TEdgeGoogleMapViewer.ShowMap here;
  try
    NavigateToURL('file:///'+LFileName);
  finally
    MapIsBusy := False;
  end;
so you can see the name of temporary file and look inside, if there are some problems: open it in your browser activating the debug tools...
