### ISSUE TITLE
HeatMap

### ISSUE THREAD

**Issue by fernandolfc1983** [EtheaDev/DelphiGoogleMap#9]
Preciso fazer um mapa de Calor, HeatMap, similar ao link:

https://geobrainstorms.wordpress.com/2013/05/23/mapa-de-calor-com-o-google-maps/

Tem um idéia de como fazer isso?

**Comment by carloBarazzetta** [comment]
The component is quite simple: uses an HTML page with google maps javascript functions inside and then calls them.
Look at the code where the html file is saved into temp folder and navigate the browser to is, so you can see the output produced by the component.
If you find a google-map javascript example to produce what you need we can expand the javascript code of the component and call the new function.

**Comment by carloBarazzetta** [comment]
I've added more help into readme.md, I hope to help you.
